version: "3.8"
services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "89:80"
    networks:
      - postgres-network

  postgres:
    image: postgres:10
    container_name: postgres10_container
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dungeons_and_dragons
    ports:
      - "5432:5432"
    networks:
      - postgres-network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dungeons_and_dragons
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

networks:
  postgres-network:
    driver: bridge